stages:
  - template: azure/stages.yml@templates
    parameters:
      nightly_coverage: true
      minrust: false

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: another-s347
